plugin:
    name: Movies
    description: 'Movies Plugin'
    author: Ffte
    icon: oc-icon-adjust
    homepage: ''
navigation:
    main-menu-item:
        label: Movies
        url: ffte/movies/movies
        icon: icon-film
        sideMenu:
            side-menu-movies:
                label: Movies
                url: ffte/movies/movies
                icon: icon-film
            side-menu-tags:
                label: Tags
                url: ffte/movies/tags
                icon: icon-tags
            side-menu-categories:
                label: Categories
                url: ffte/movies/categories
                icon: icon-sitemap
