plugin:
    name: Movies
    description: 'Movies Plugin'
    author: Ffte
    icon: oc-icon-adjust
    homepage: ''
navigation:
    main-menu-item:
        label: Movies
        url: ffte/movies/movies
        icon: icon-film
        sideMenu:
            side-menu-movies:
                label: Movies
                url: ffte/movies/movies
                icon: icon-film
            side-menu-tags:
                label: Tags
                url: ffte/movies/tags
                icon: icon-tags
                permissions:
                    - ffte.movies.tags
            side-menu-categories:
                label: Categories
                url: ffte/movies/categories
                icon: icon-folder
            side-menu-clips:
                label: Clips
                url: ffte/movies/clips
                icon: icon-video-camera
            side-menu-people:
                label: People
                url: ffte/movies/people
                icon: icon-users
            side-menu-links:
                label: Links
                url: ffte/movies/links
                icon: icon-external-link
            side-menu-rights:
                label: Rightsholders
                url: ffte/movies/rightsholders
                icon: icon-copyright
permissions:
    ffte.movies.tags:
        tab: Movies
        label: Tags
