plugin:
    name: Movies
    description: 'Movies Plugin'
    author: Ffte
    icon: oc-icon-adjust
    homepage: ''
navigation:
    main-menu-item:
        label: Movies
        url: ffte/movies/movies
        icon: icon-film
        sideMenu:
            side-menu-movies:
                label: Movies
                url: ffte/movies/movies
                icon: icon-film
            side-menu-tags:
                label: Tags
                url: ffte/movies/tags
                icon: icon-tags
                permissions:
                    - ffte.movies.tags
            side-menu-categories:
                label: Categories
                url: ffte/movies/categories
                icon: icon-folder
            side-menu-media:
                label: Media
                url: ffte/movies/media
                icon: icon-camera
            side-menu-providers:
                label: Providers
                url: ffte/movies/providers
                icon: icon-sitemap
            side-menu-people:
                label: People
                url: ffte/movies/people
                icon: icon-users
            side-menu-countries:
                label: Countries
                url: ffte/movies/countries
                icon: icon-flag
            side-menu-language:
                label: Languages
                url: ffte/movies/languages
                icon: icon-language
            side-menu-links:
                label: Links
                url: ffte/movies/links
                icon: icon-external-link
permissions:
    ffte.movies.tags:
        tab: Movies
        label: Tags
