plugin:
    name: Movies
    description: 'Movies Plugin'
    author: Ffte
    icon: oc-icon-adjust
    homepage: ''
navigation:
    main-menu-item:
        label: Movies
        url: ffte/movies/movies
        icon: icon-film
        sideMenu:
            side-menu-movies:
                label: Movies
                url: ffte/movies/movies
                icon: icon-film
            side-menu-tags:
                label: Tags
                url: ffte/movies/tags
                icon: icon-tags
                permissions:
                    - ffte.movies.tags
            side-menu-categories:
                label: Categories
                url: ffte/movies/categories
                icon: icon-sitemap
            side-menu-media:
                label: Media
                url: ffte/movies/media
                icon: icon-sitemap
            side-menu-providers:
                label: Providers
                url: ffte/movies/providers
                icon: icon-sitemap
permissions:
    ffte.movies.tags:
        tab: Movies
        label: Tags
