list: $/ffte/movies/models/collection/columns.yaml
modelClass: Ffte\Movies\Models\Collection
title: Collections
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
recordUrl: 'ffte/movies/collections/update/:id'
