title: Clips
modelClass: Ffte\Movies\Models\Clip
list: $/ffte/movies/models/clip/columns.yaml
recordUrl: 'ffte/movies/clips/update/:id'
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
# Records to display per page
recordsPerPage: 20
filter: config_filter.yaml
