list: $/ffte/movies/models/linktype/columns.yaml
modelClass: Ffte\Movies\Models\LinkType
title: LinkTypes
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
recordUrl: 'ffte/movies/linktypes/update/:id'
