list: $/ffte/movies/models/country/columns.yaml
modelClass: Ffte\Movies\Models\Country
title: Countries
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
recordUrl: 'ffte/movies/countries/update/:id'
