list: $/ffte/movies/models/language/columns.yaml
modelClass: Ffte\Movies\Models\Language
title: Languages
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
recordUrl: 'ffte/movies/languages/update/:id'
