# ===================================
#  Form Behavior Config
# ===================================

# Record name
name: Provider

# Model Form Field configuration
form: $/ffte/movies/models/mediaprovider/fields.yaml

# Model Class name
modelClass: Ffte\Movies\Models\MediaProvider

# Default redirect location
defaultRedirect: ffte/movies/providers

# Create page
create:
    title: Create Provider
    redirect: ffte/movies/providers/update/:id
    redirectClose: ffte/movies/providers

# Update page
update:
    title: Edit Provider
    redirect: ffte/movies/providers
    redirectClose: ffte/movies/providers

# Preview page
preview:
    title: Preview Provider
