list: $/ffte/movies/models/cliptype/columns.yaml
modelClass: Ffte\Movies\Models\ClipType
title: ClipFormats
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
recordUrl: 'ffte/movies/clipformats/update/:id'
