
clips:
  label: Clips
  view:
    list: $/ffte/movies/models/clip/columns.yaml
    toolbarButtons: create|add|delete|remove
  manage:
    form: $/ffte/movies/models/clip/fields.yaml

links:
  label: Links
  view:
    list: $/ffte/movies/models/link/columns.yaml
    toolbarButtons: create|delete
  manage:
    form: $/ffte/movies/models/link/fields.yaml

vod_services:
  label: VOD Services
  view:
    list: $/ffte/movies/models/vodservice/columns.yaml
    toolbarButtons: create|delete
  manage:
    form: $/ffte/movies/models/vodservice/fields.yaml

ratings:
  label: Ratings
  view:
    list: $/ffte/movies/models/rating/columns.yaml
    toolbarButtons: create|delete
  manage:
    form: $/ffte/movies/models/rating/fields.yaml
