list: $/ffte/movies/models/movie/columns.yaml
modelClass: Ffte\Movies\Models\Movie
title: Movies
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
recordUrl: 'ffte/movies/movies/update/:id'
recordsPerPage: 20
filter: config_filter.yaml