list: $/ffte/movies/models/right/columns.yaml
modelClass: Ffte\Movies\Models\Right
title: Rights
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
recordUrl: 'ffte/movies/rights/update/:id'
